name: Build and Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-windows:
        runs-on: windows-2022
        steps:
            - uses: lukka/get-cmake@latest
              with:
                cmakeVersion: 3.26.3
                ninjaVersion: 1.11.1
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Configure, Build
              run: |
                 cmake -S . -B build -G "Ninja" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-static"
                 cmake --build build
            - name: Generate build number
              id: buildnumber
              uses: onyxmueller/build-tag-number@v1.0.3
              with:
                token: ${{secrets.github_token}}
            - name: Release Binary
              uses: softprops/action-gh-release@v0.1.15
              with:
                files: build/hexcode.exe
                tag_name: ${{ format('AutoRelease-{0}', steps.buildnumber.outputs.build_number) }}
